#:include kv/homescreen.kv
#:include kv/loginscreen.kv
#:include kv/checkboxscreen.kv

GridLayout:
    cols: 1
    ScreenManager:
        id: screen_manager
        LoginScreen:
            name: "login_screen"
            id: login_screen
        HomeScreen:
            name: "home_screen"
            id: home_screen
        CheckBoxScreen:
            name: "checkbox_screen"
            id: checkbox_screen


